'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { AonFooter as AonFooterElement, defineCustomElement as defineAonFooter } from "@trustcenter/components/dist/components/aon-footer.js";
import { AonNavbar as AonNavbarElement, defineCustomElement as defineAonNavbar } from "@trustcenter/components/dist/components/aon-navbar.js";
import { ExpansionCard as ExpansionCardElement, defineCustomElement as defineExpansionCard } from "@trustcenter/components/dist/components/expansion-card.js";
import { FaqCard as FaqCardElement, defineCustomElement as defineFaqCard } from "@trustcenter/components/dist/components/faq-card.js";
import { LinkCard as LinkCardElement, defineCustomElement as defineLinkCard } from "@trustcenter/components/dist/components/link-card.js";
import React from 'react';

type AonFooterEvents = NonNullable<unknown>;

export const AonFooter: StencilReactComponent<AonFooterElement, AonFooterEvents> = /*@__PURE__*/ createComponent<AonFooterElement, AonFooterEvents>({
    tagName: 'aon-footer',
    elementClass: AonFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as AonFooterEvents,
    defineCustomElement: defineAonFooter
});

type AonNavbarEvents = NonNullable<unknown>;

export const AonNavbar: StencilReactComponent<AonNavbarElement, AonNavbarEvents> = /*@__PURE__*/ createComponent<AonNavbarElement, AonNavbarEvents>({
    tagName: 'aon-navbar',
    elementClass: AonNavbarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as AonNavbarEvents,
    defineCustomElement: defineAonNavbar
});

type ExpansionCardEvents = NonNullable<unknown>;

export const ExpansionCard: StencilReactComponent<ExpansionCardElement, ExpansionCardEvents> = /*@__PURE__*/ createComponent<ExpansionCardElement, ExpansionCardEvents>({
    tagName: 'expansion-card',
    elementClass: ExpansionCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ExpansionCardEvents,
    defineCustomElement: defineExpansionCard
});

type FaqCardEvents = { onToggleFaq: EventName<CustomEvent<void>> };

export const FaqCard: StencilReactComponent<FaqCardElement, FaqCardEvents> = /*@__PURE__*/ createComponent<FaqCardElement, FaqCardEvents>({
    tagName: 'faq-card',
    elementClass: FaqCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onToggleFaq: 'toggleFaq' } as FaqCardEvents,
    defineCustomElement: defineFaqCard
});

type LinkCardEvents = NonNullable<unknown>;

export const LinkCard: StencilReactComponent<LinkCardElement, LinkCardEvents> = /*@__PURE__*/ createComponent<LinkCardElement, LinkCardEvents>({
    tagName: 'link-card',
    elementClass: LinkCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as LinkCardEvents,
    defineCustomElement: defineLinkCard
});
