FROM oven/bun:1.3.11

WORKDIR /app

ENV HUSKY=0

COPY package.json bun.lock ./
COPY stencil/package.json ./stencil/package.json

RUN bun install --frozen-lockfile

COPY . .

EXPOSE 4000

CMD ["bun", "run", "dev:server:start"]
