FROM oven/bun:1.3.11

WORKDIR /app

ENV HUSKY=0

COPY package.json bun.lock ./
COPY stencil/package.json ./stencil/package.json

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build:stencil

EXPOSE 5173

CMD ["bun", "run", "dev:client"]
