/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AonBlueCard {
        "blueCardButtonLink": string;
        "blueCardButtonText": string;
        "blueCardDescription": string;
        "blueCardTitle": string;
    }
    interface AonControlCard {
        /**
          * @default []
         */
        "controlCardSubtitle": string[];
        /**
          * @default []
         */
        "controlCardSubtitleDescription": string[];
        "controlCardTitle": string;
        "controlStatusText": string;
        "greenDotIcon": string;
    }
    interface AonFooter {
        /**
          * @default '© Aon plc'
         */
        "copyright": string;
        "logoSrc": string;
        /**
          * @default '/privacy-policy'
         */
        "privacyPolicyHref": string;
        /**
          * @default '/terms-and-conditions'
         */
        "termsHref": string;
    }
    interface AonHeader {
        "CyQuLogo": string;
        "loginIcon": string;
    }
    interface AonNavbar {
    }
    interface AonSubnavCard {
        /**
          * @default "Data and Privacy"
         */
        "dataAndPrivacyHref": string;
        /**
          * @default "Infrastructure Security"
         */
        "infrastructureSecurityHref": string;
        /**
          * @default "Internal Security Procedures"
         */
        "internalSecurityProceduresHref": string;
        /**
          * @default "Organizational Security"
         */
        "organizationalSecurityHref": string;
        /**
          * @default "Product Security"
         */
        "productSecurityHref": string;
        /**
          * @default "Categories"
         */
        "subnavCardTitle": string;
    }
    interface AonTitle {
        /**
          * @default "cyber.security.support@email.com"
         */
        "supportEmail": string;
        /**
          * @default "Resources to address common cyber security questions from clients"
         */
        "supportMessage": string;
        /**
          * @default "Trust Center"
         */
        "trustCenterName": string;
    }
    interface ExpansionCard {
        /**
          * Bullet content provided by backend or CMS
          * @default []
         */
        "bulletPoints": string[];
        /**
          * Display title for the card
         */
        "expansionCardTitle": string;
        /**
          * Optional icon URL used to replace default list markers
         */
        "icon"?: string;
    }
    interface FaqCard {
        /**
          * Answer content displayed when expanded
         */
        "answer": string;
        /**
          * Controlled expansion state (owned by React)
          * @default false
         */
        "expanded": boolean;
        /**
          * FAQ prompt text
         */
        "question": string;
    }
    interface LinkCard {
        /**
          * Card heading
         */
        "linkCardTitle": string;
        "linkOneHref": string;
        /**
          * Link 1
         */
        "linkOneLabel": string;
        "linkThreeHref": string;
        /**
          * Link 3
         */
        "linkThreeLabel": string;
        "linkTwoHref": string;
        /**
          * Link 2
         */
        "linkTwoLabel": string;
    }
}
export interface FaqCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFaqCardElement;
}
declare global {
    interface HTMLAonBlueCardElement extends Components.AonBlueCard, HTMLStencilElement {
    }
    var HTMLAonBlueCardElement: {
        prototype: HTMLAonBlueCardElement;
        new (): HTMLAonBlueCardElement;
    };
    interface HTMLAonControlCardElement extends Components.AonControlCard, HTMLStencilElement {
    }
    var HTMLAonControlCardElement: {
        prototype: HTMLAonControlCardElement;
        new (): HTMLAonControlCardElement;
    };
    interface HTMLAonFooterElement extends Components.AonFooter, HTMLStencilElement {
    }
    var HTMLAonFooterElement: {
        prototype: HTMLAonFooterElement;
        new (): HTMLAonFooterElement;
    };
    interface HTMLAonHeaderElement extends Components.AonHeader, HTMLStencilElement {
    }
    var HTMLAonHeaderElement: {
        prototype: HTMLAonHeaderElement;
        new (): HTMLAonHeaderElement;
    };
    interface HTMLAonNavbarElement extends Components.AonNavbar, HTMLStencilElement {
    }
    var HTMLAonNavbarElement: {
        prototype: HTMLAonNavbarElement;
        new (): HTMLAonNavbarElement;
    };
    interface HTMLAonSubnavCardElement extends Components.AonSubnavCard, HTMLStencilElement {
    }
    var HTMLAonSubnavCardElement: {
        prototype: HTMLAonSubnavCardElement;
        new (): HTMLAonSubnavCardElement;
    };
    interface HTMLAonTitleElement extends Components.AonTitle, HTMLStencilElement {
    }
    var HTMLAonTitleElement: {
        prototype: HTMLAonTitleElement;
        new (): HTMLAonTitleElement;
    };
    interface HTMLExpansionCardElement extends Components.ExpansionCard, HTMLStencilElement {
    }
    var HTMLExpansionCardElement: {
        prototype: HTMLExpansionCardElement;
        new (): HTMLExpansionCardElement;
    };
    interface HTMLFaqCardElementEventMap {
        "toggleFaq": void;
    }
    interface HTMLFaqCardElement extends Components.FaqCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFaqCardElementEventMap>(type: K, listener: (this: HTMLFaqCardElement, ev: FaqCardCustomEvent<HTMLFaqCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFaqCardElementEventMap>(type: K, listener: (this: HTMLFaqCardElement, ev: FaqCardCustomEvent<HTMLFaqCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFaqCardElement: {
        prototype: HTMLFaqCardElement;
        new (): HTMLFaqCardElement;
    };
    interface HTMLLinkCardElement extends Components.LinkCard, HTMLStencilElement {
    }
    var HTMLLinkCardElement: {
        prototype: HTMLLinkCardElement;
        new (): HTMLLinkCardElement;
    };
    interface HTMLElementTagNameMap {
        "aon-blue-card": HTMLAonBlueCardElement;
        "aon-control-card": HTMLAonControlCardElement;
        "aon-footer": HTMLAonFooterElement;
        "aon-header": HTMLAonHeaderElement;
        "aon-navbar": HTMLAonNavbarElement;
        "aon-subnav-card": HTMLAonSubnavCardElement;
        "aon-title": HTMLAonTitleElement;
        "expansion-card": HTMLExpansionCardElement;
        "faq-card": HTMLFaqCardElement;
        "link-card": HTMLLinkCardElement;
    }
}
declare namespace LocalJSX {
    interface AonBlueCard {
        "blueCardButtonLink"?: string;
        "blueCardButtonText"?: string;
        "blueCardDescription"?: string;
        "blueCardTitle"?: string;
    }
    interface AonControlCard {
        /**
          * @default []
         */
        "controlCardSubtitle"?: string[];
        /**
          * @default []
         */
        "controlCardSubtitleDescription"?: string[];
        "controlCardTitle"?: string;
        "controlStatusText"?: string;
        "greenDotIcon"?: string;
    }
    interface AonFooter {
        /**
          * @default '© Aon plc'
         */
        "copyright"?: string;
        "logoSrc": string;
        /**
          * @default '/privacy-policy'
         */
        "privacyPolicyHref"?: string;
        /**
          * @default '/terms-and-conditions'
         */
        "termsHref"?: string;
    }
    interface AonHeader {
        "CyQuLogo"?: string;
        "loginIcon"?: string;
    }
    interface AonNavbar {
    }
    interface AonSubnavCard {
        /**
          * @default "Data and Privacy"
         */
        "dataAndPrivacyHref"?: string;
        /**
          * @default "Infrastructure Security"
         */
        "infrastructureSecurityHref"?: string;
        /**
          * @default "Internal Security Procedures"
         */
        "internalSecurityProceduresHref"?: string;
        /**
          * @default "Organizational Security"
         */
        "organizationalSecurityHref"?: string;
        /**
          * @default "Product Security"
         */
        "productSecurityHref"?: string;
        /**
          * @default "Categories"
         */
        "subnavCardTitle"?: string;
    }
    interface AonTitle {
        /**
          * @default "cyber.security.support@email.com"
         */
        "supportEmail"?: string;
        /**
          * @default "Resources to address common cyber security questions from clients"
         */
        "supportMessage"?: string;
        /**
          * @default "Trust Center"
         */
        "trustCenterName"?: string;
    }
    interface ExpansionCard {
        /**
          * Bullet content provided by backend or CMS
          * @default []
         */
        "bulletPoints"?: string[];
        /**
          * Display title for the card
         */
        "expansionCardTitle": string;
        /**
          * Optional icon URL used to replace default list markers
         */
        "icon"?: string;
    }
    interface FaqCard {
        /**
          * Answer content displayed when expanded
         */
        "answer": string;
        /**
          * Controlled expansion state (owned by React)
          * @default false
         */
        "expanded"?: boolean;
        /**
          * User intent: toggle expand / collapse
         */
        "onToggleFaq"?: (event: FaqCardCustomEvent<void>) => void;
        /**
          * FAQ prompt text
         */
        "question": string;
    }
    interface LinkCard {
        /**
          * Card heading
         */
        "linkCardTitle": string;
        "linkOneHref": string;
        /**
          * Link 1
         */
        "linkOneLabel": string;
        "linkThreeHref": string;
        /**
          * Link 3
         */
        "linkThreeLabel": string;
        "linkTwoHref": string;
        /**
          * Link 2
         */
        "linkTwoLabel": string;
    }
    interface IntrinsicElements {
        "aon-blue-card": AonBlueCard;
        "aon-control-card": AonControlCard;
        "aon-footer": AonFooter;
        "aon-header": AonHeader;
        "aon-navbar": AonNavbar;
        "aon-subnav-card": AonSubnavCard;
        "aon-title": AonTitle;
        "expansion-card": ExpansionCard;
        "faq-card": FaqCard;
        "link-card": LinkCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aon-blue-card": LocalJSX.AonBlueCard & JSXBase.HTMLAttributes<HTMLAonBlueCardElement>;
            "aon-control-card": LocalJSX.AonControlCard & JSXBase.HTMLAttributes<HTMLAonControlCardElement>;
            "aon-footer": LocalJSX.AonFooter & JSXBase.HTMLAttributes<HTMLAonFooterElement>;
            "aon-header": LocalJSX.AonHeader & JSXBase.HTMLAttributes<HTMLAonHeaderElement>;
            "aon-navbar": LocalJSX.AonNavbar & JSXBase.HTMLAttributes<HTMLAonNavbarElement>;
            "aon-subnav-card": LocalJSX.AonSubnavCard & JSXBase.HTMLAttributes<HTMLAonSubnavCardElement>;
            "aon-title": LocalJSX.AonTitle & JSXBase.HTMLAttributes<HTMLAonTitleElement>;
            "expansion-card": LocalJSX.ExpansionCard & JSXBase.HTMLAttributes<HTMLExpansionCardElement>;
            "faq-card": LocalJSX.FaqCard & JSXBase.HTMLAttributes<HTMLFaqCardElement>;
            "link-card": LocalJSX.LinkCard & JSXBase.HTMLAttributes<HTMLLinkCardElement>;
        }
    }
}
