/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AonFooter {
        /**
          * @default '© Aon plc'
         */
        "copyright": string;
        "logoSrc": string;
        /**
          * @default '/privacy-policy'
         */
        "privacyPolicyHref": string;
        /**
          * @default '/terms-and-conditions'
         */
        "termsHref": string;
    }
    interface AonNavbar {
    }
    interface ExpansionCard {
        /**
          * Bullet content provided by backend or CMS
          * @default []
         */
        "bulletPoints": string[];
        /**
          * Display title for the card
         */
        "expansionCardTitle": string;
        /**
          * Optional icon URL used to replace default list markers
         */
        "icon"?: string;
    }
    interface FaqCard {
        /**
          * Answer content displayed when expanded
         */
        "answer": string;
        /**
          * Controlled expansion state (owned by React)
          * @default false
         */
        "expanded": boolean;
        /**
          * FAQ prompt text
         */
        "question": string;
    }
    interface LinkCard {
        /**
          * Display title for the card
         */
        "linkCardTitle": string;
        /**
          * Ordered list of navigation links
          * @default []
         */
        "links": Array<{ label: string; href: string }>;
    }
}
export interface FaqCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFaqCardElement;
}
declare global {
    interface HTMLAonFooterElement extends Components.AonFooter, HTMLStencilElement {
    }
    var HTMLAonFooterElement: {
        prototype: HTMLAonFooterElement;
        new (): HTMLAonFooterElement;
    };
    interface HTMLAonNavbarElement extends Components.AonNavbar, HTMLStencilElement {
    }
    var HTMLAonNavbarElement: {
        prototype: HTMLAonNavbarElement;
        new (): HTMLAonNavbarElement;
    };
    interface HTMLExpansionCardElement extends Components.ExpansionCard, HTMLStencilElement {
    }
    var HTMLExpansionCardElement: {
        prototype: HTMLExpansionCardElement;
        new (): HTMLExpansionCardElement;
    };
    interface HTMLFaqCardElementEventMap {
        "toggleFaq": void;
    }
    interface HTMLFaqCardElement extends Components.FaqCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFaqCardElementEventMap>(type: K, listener: (this: HTMLFaqCardElement, ev: FaqCardCustomEvent<HTMLFaqCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFaqCardElementEventMap>(type: K, listener: (this: HTMLFaqCardElement, ev: FaqCardCustomEvent<HTMLFaqCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFaqCardElement: {
        prototype: HTMLFaqCardElement;
        new (): HTMLFaqCardElement;
    };
    interface HTMLLinkCardElement extends Components.LinkCard, HTMLStencilElement {
    }
    var HTMLLinkCardElement: {
        prototype: HTMLLinkCardElement;
        new (): HTMLLinkCardElement;
    };
    interface HTMLElementTagNameMap {
        "aon-footer": HTMLAonFooterElement;
        "aon-navbar": HTMLAonNavbarElement;
        "expansion-card": HTMLExpansionCardElement;
        "faq-card": HTMLFaqCardElement;
        "link-card": HTMLLinkCardElement;
    }
}
declare namespace LocalJSX {
    interface AonFooter {
        /**
          * @default '© Aon plc'
         */
        "copyright"?: string;
        "logoSrc": string;
        /**
          * @default '/privacy-policy'
         */
        "privacyPolicyHref"?: string;
        /**
          * @default '/terms-and-conditions'
         */
        "termsHref"?: string;
    }
    interface AonNavbar {
    }
    interface ExpansionCard {
        /**
          * Bullet content provided by backend or CMS
          * @default []
         */
        "bulletPoints"?: string[];
        /**
          * Display title for the card
         */
        "expansionCardTitle": string;
        /**
          * Optional icon URL used to replace default list markers
         */
        "icon"?: string;
    }
    interface FaqCard {
        /**
          * Answer content displayed when expanded
         */
        "answer": string;
        /**
          * Controlled expansion state (owned by React)
          * @default false
         */
        "expanded"?: boolean;
        /**
          * User intent: toggle expand / collapse
         */
        "onToggleFaq"?: (event: FaqCardCustomEvent<void>) => void;
        /**
          * FAQ prompt text
         */
        "question": string;
    }
    interface LinkCard {
        /**
          * Display title for the card
         */
        "linkCardTitle": string;
        /**
          * Ordered list of navigation links
          * @default []
         */
        "links"?: Array<{ label: string; href: string }>;
    }
    interface IntrinsicElements {
        "aon-footer": AonFooter;
        "aon-navbar": AonNavbar;
        "expansion-card": ExpansionCard;
        "faq-card": FaqCard;
        "link-card": LinkCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aon-footer": LocalJSX.AonFooter & JSXBase.HTMLAttributes<HTMLAonFooterElement>;
            "aon-navbar": LocalJSX.AonNavbar & JSXBase.HTMLAttributes<HTMLAonNavbarElement>;
            "expansion-card": LocalJSX.ExpansionCard & JSXBase.HTMLAttributes<HTMLExpansionCardElement>;
            "faq-card": LocalJSX.FaqCard & JSXBase.HTMLAttributes<HTMLFaqCardElement>;
            "link-card": LocalJSX.LinkCard & JSXBase.HTMLAttributes<HTMLLinkCardElement>;
        }
    }
}
